application: random-guardian
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/(.*)
- url: /static
  static_dir: static
- url: .*
  script: main.py
